//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app27122018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int EmpleadoID { get; set; }
        public string Apelido { get; set; }
        public string Nombre { get; set; }
        public string Puesto { get; set; }
        public string Loguin { get; set; }
        public string contrasena { get; set; }
    
        public virtual Jornadas Jornadas { get; set; }
    }
}
